## CONFIG file
## change paths with your own!

deterministic: False
seed: 100

trainset_path: "/fast/najroldi/data/lm/fwedu/fwedu_sample_10BT/tokenized_EleutherAI_gpt-neox-20b/ctx_2048/train" # tokens: 9_849_288_704
vocab_size: 50277
seq_len: 2048
intra_doc_masking: False
sampler: 'stateful_random'
sampler_seed: 1996
num_workers: 4

eval: True
validset_path: "/fast/najroldi/data/lm/fwedu/fwedu_sample_10BT/tokenized_EleutherAI_gpt-neox-20b/ctx_2048/valid"
valid_tokens: 1000000  # 1M
eval_every_steps: 100

model: 'pythia-70m'
torch_compile: True

# Allow TF32 matmul for speedups on Ampere+ GPUs
cuda_matmul_allow_tf32: True
cudnn_allow_tf32: True

# note: step budget=token_budget/(seq_len * micro_batch_size * grad_accumulation_steps * ddp_world_size)
steps_budget: 2000

# note: this is micro batch size if grad_accumulation_steps>1
# note: with ddp, effective batch size = batch_size * grad_accumulation_steps * ddp_world_size
micro_batch_size: 32
grad_accumulation_steps: 2

# note: choose between {float32, float16, bfloat16}
# note: float16 data type will automatically use a GradScaler
dtype: 'bfloat16'
optim: 'adamw'
fused_optim: True
lr: 0.01
weight_decay: 0.1
beta1: 0.9
beta2: 0.95
grad_clip: 1.0
log_grad_norms: False

scheduler: 'oneminsqrt_frominvsqrt_cooldown'
warmup_steps: 0.1
cooldown_steps: 400
lr_start: 0.0
lr_end: 0.0
lr_end_pct: null

log_every_steps: 1
print_progress: True

use_wandb: True
wandb_project: 'wa_lm_3'
wandb_dir: '/fast/najroldi/logs/wa_lm_3/wandb'
wandb_run_name: 'nld_invsqrt_cooldown_01'
exp_name: 'nld_invsqrt_cooldown_01'
out_dir: '/fast/najroldi/exp/wa_lm_3'
over_write: True

resume: True 
resume_exp_name: "/fast/najroldi/exp/wa_lm_3/nld_invsqrt_save_01/job_idx_0"
resume_step: [200, 400, 600, 800, 1000, 1200, 1400, 1600] # 8x

save_last_checkpoint: True
save_intermediate_checkpoints: False
save_every_steps: null # save the model every X steps
save_optim_every_steps: null # save optimizer every Y steps (if not specified, will default to save_every_steps)
