# trainset: 99_762_225_152 (~100BT)
# validset:      9_994_240 (~10MT)

deterministic: False
seed: 100

trainset_path: "/fast/najroldi/data/lm/fwedu/fwedu_sample_100BT/tokenized_EleutherAI_gpt-neox-20b/ctx_2048/train"
vocab_size: 50277
seq_len: 2048
intra_doc_masking: False
sampler: 'stateful_random'
sampler_seed: 1996
num_workers: 4

eval: False
validset_path: "/fast/najroldi/data/lm/fwedu/fwedu_sample_100BT/tokenized_EleutherAI_gpt-neox-20b/ctx_2048/valid"
valid_tokens: null
eval_every_steps: null

model: 'transformer'
mlp_class: 'glu'
expand: '8/3'
rms_norm: True
tie_embeddings: False
torch_compile: True

# 49M
n_layers: 6
d_model: 384
n_heads: 6
micro_batch_size: 32

# Allow TF32 matmul and cudnn
cuda_matmul_allow_tf32: True
cudnn_allow_tf32: True

# note: step budget=token_budget/(seq_len * micro_batch_size * grad_accumulation_steps * ddp_world_size)
steps_budget: 20000 # 10_485_760_000 tokens

# note: this is micro batch size if grad_accumulation_steps>1
# note: with ddp, effective batch size = batch_size * grad_accumulation_steps * ddp_world_size
grad_accumulation_steps: 2

# note: choose between {float32, float16, bfloat16}
# note: float16 data type will automatically use a GradScaler
dtype: 'bfloat16'

optim: 'adamw'
fused_optim: True
lr: [1.e-3, 3.e-3]
weight_decay: 0.1
beta1: 0.9
beta2: 0.95
grad_clip: 1.0

scheduler: 'wsd'
warmup_steps: 0.05
cooldown_steps: 4000
lr_start: 0.0
lr_end: 0.0
lr_end_pct: null

log_every_steps: 50
print_progress: True

use_wandb: True
wandb_project: 'quant'
wandb_dir: '/fast/najroldi/logs/quant/wandb'
wandb_run_name: 'scaling_n_lr_50M_02'
exp_name: 'scaling_n_lr_50M_02'
out_dir: '/fast/najroldi/exp/quant'
over_write: True

resume: False
resume_step: null
resume_exp_name: null

save_last_checkpoint: True
save_intermediate_checkpoints: True
save_every_steps: 500 # save the model every X steps
save_optim_every_steps: 500 # save optimizer every Y steps
